# permissions for end users to view tasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: task-operator
    app.kubernetes.io/managed-by: kustomize
  name: task-viewer-role
rules:
- apiGroups:
  - custom.io.intuit.com
  resources:
  - tasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - custom.io.intuit.com
  resources:
  - tasks/status
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - cronjob
  - job
  verbs:
  - get
  - list
  - watch