apiVersion: custom.io.intuit.com/v1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: task-operator
    app.kubernetes.io/managed-by: kustomize
  name: task-sample
spec:
  # TODO(user): Add fields here
